### ISSUE TITLE
Link to the Models and Data folder is invalid        

### ISSUE THREAD

**Issue by kailigo** [nicola-decao/KnowledgeEditor#2]
Nice work, but it seems the link is invalid. Could you check what is going on.

Besides, still waiting instructions to run the code and  reproduce the results. Thanks.

**Comment by nicola-decao** [comment]
What link are you referring to?

**Comment by kailigo** [comment]
The one links to the datasets and base models you provided in the README

**Comment by nicola-decao** [comment]
The link works for me. Maybe try another browser?

**Comment by eric-mitchell** [comment]
I can confirm the link worked for me on Safari

**Comment by nicola-decao** [comment]
@kailigo they work for me from Chrome. Maybe try to change browser?
