### ISSUE TITLE
Cannot run the code

### ISSUE THREAD

**Issue by xingbow** [nicola-decao/KnowledgeEditor#3]
Can not run the code for `train_bert_binary_augmented_kilt.sh`
First, it says ModuleNotFoundError: No module named 'pytorch_lightning.metrics'. Then, I import `torchmetrics`
and change the original lines of `pl.metrics.Accuracy()` to `torchmetrics.Accuracy()`. The code can work.
However, new problems occur in https://github.com/nicola-decao/KnowledgeEditor/blob/668aca6d01cc12e9a5fda17fe29a2334b6d0a359/src/models/bert_binary_augmented_kilt.py#L257 with the message below:
`
ValueError: The `target` has to be an integer tensor.
`

Please advise how to debug it.

**Comment by xingbow** [comment]
# Update
Currently, I found a workaround fix for the bug. I may need @nicola-decao 's verification.
The fix is 1) adding some code before the quoted line https://github.com/nicola-decao/KnowledgeEditor/blob/668aca6d01cc12e9a5fda17fe29a2334b6d0a359/src/models/bert_binary_augmented_kilt.py#L257
```
logits = (torch.sigmoid(logits) > 0.5).int()

```
And 2) add `.int()` for `batch["labels"]` in the function
https://github.com/nicola-decao/KnowledgeEditor/blob/668aca6d01cc12e9a5fda17fe29a2334b6d0a359/src/models/bert_binary_augmented_kilt.py#L253

**Comment by nicola-decao** [comment]
This error occurs because you are using a newer version of `pytorch-lightning` than I used. Your fix is fine for that version but I fixed `requirements.txt` accordingly
