### ISSUE TITLE
Validation step error when training bert binary augmented

### ISSUE THREAD

**Issue by gianlucagiudice** [nicola-decao/KnowledgeEditor#4]
I'm using `python3.8.7` with the libraries in the `requirement.txt`

I have a problem when running: 
`train_bert_binary_augmented_kilt.py`

I got: `ValueError: The 'target' has to be an integer tensor.` at the following line:
https://github.com/nicola-decao/KnowledgeEditor/blob/80b86e41a780161b5479862184d5d0b62f579acf/src/models/bert_binary_augmented_kilt.py#L257

Indeed `batch["labels"]` is a Tensor with `dtype` = `torch.float32`. I tried to cast the tensor to integer with `batch['labels'].to(torch.int)`. It works but then i got:

`ValueError: The 'preds' should be probabilities, but values were detected outside of [0,1] range.`

So I changed `logits` with:
`torch.IntTensor([x > 0 for x in logits])`

The same holds for these lines:
https://github.com/nicola-decao/KnowledgeEditor/blob/80b86e41a780161b5479862184d5d0b62f579acf/src/models/bert_binary_augmented_kilt.py#L262-L265

Is this a viable fix? Thank you.

**Comment by nicola-decao** [comment]
Did you use `torch==1.7` and `pytorch_lightning==1.2`?

**Comment by gianlucagiudice** [comment]
Here is the output of : `pip freeze | grep "torch"`    

```
pytorch-lightning==1.2.0
torch==1.7.0
torchvision==0.8.1
```

**Comment by nicola-decao** [comment]
try if the new code works pls

**Comment by gianlucagiudice** [comment]
Thank you, it works perfectly!
