### ISSUE TITLE
Runtime error when using DDP 

### ISSUE THREAD

**Issue by himanshubeniwal** [nicola-decao/KnowledgeEditor#5]
Hii, I just wanted to highlight that when using the 'ddp' with the following command:
`python scripts/train_bert_binary_augmented_kilt.py     --gpus 1     --accelerator ddp     --num_workers 32     --batch_size 256     --max_steps 50000     --divergences kl`

There is an error: 
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by (1) passing the keyword argument _find_unused_parameters=True_ to _torch.nn.parallel.DistributedDataParallel;_ (2) making sure all `forward` function outputs participate in calculating loss. If you already have done the above two steps, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).

But after removing the _--accelerator ddp_, it is running fine. Is there any workaround to use it with DDP? I have tried setting `find_unused_parameters=True to torch.nn.parallel.DistributedDataParallel;`. But somehow this is also not working.

**Comment by nicola-decao** [comment]
I didn't train on multiple GPUs, mainly because I do not know how to sync the hyper-network across processes.
